<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ArtistMirror</RootNamespace>
    <AssemblyName>ArtistMirror</AssemblyName>
    <Product>artist-mirror</Product>
    <AssemblyTitle>artist-mirror</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArtistMirror.Tests" />
  </ItemGroup>

</Project>